In [1]:
import numpy as np

In [30]:
a=np.array([2,4,5,6,8,9,45], dtype = "int64")

In [31]:
a.dtype

dtype('int64')

In [4]:
type(a)

numpy.ndarray

In [6]:
b=np.array([[3,4,5,6],[4,5,7,9]])

In [7]:
b

array([[3, 4, 5, 6],
       [4, 5, 7, 9]])

In [8]:
b.shape

(2, 4)

In [9]:
c=np.array([[2,3,4,5],[3,4,5,7]])

In [10]:
c

array([[2, 3, 4, 5],
       [3, 4, 5, 7]])

In [11]:
c+b

array([[ 5,  7,  9, 11],
       [ 7,  9, 12, 16]])

In [12]:
c.argmax()

7

In [15]:
r=np.zeros([10,5])

In [16]:
r

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
r + 6

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [39]:
r + 100000

array([[100000., 100000., 100000., 100000., 100000.],
       [100000., 100000., 100000., 100000., 100000.],
       [100000., 100000., 100000., 100000., 100000.],
       [100000., 100000., 100000., 100000., 100000.],
       [100000., 100000., 100000., 100000., 100000.],
       [100000., 100000., 100000., 100000., 100000.],
       [100000., 100000., 100000., 100000., 100000.],
       [100000., 100000., 100000., 100000., 100000.],
       [100000., 100000., 100000., 100000., 100000.],
       [100000., 100000., 100000., 100000., 100000.]])

In [36]:
r.shape]

SyntaxError: unmatched ']' (<ipython-input-36-f76be01a50ba>, line 1)

In [18]:
y=np.ones([100,40])

In [19]:
y

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [20]:
y.shape

(100, 40)

In [21]:
c*b

array([[ 6, 12, 20, 30],
       [12, 20, 35, 63]])

In [23]:
np.dot(b,c)

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [25]:
c.sum()

33

In [28]:
a=[1,2,3,4,5,6,7,8,9,10,11,12]

In [41]:
raja=np.array([[2,3,4],[5,6,7],[2,3,7]])

In [43]:
raja.shape


(3, 3)

In [44]:
raja

array([[2, 3, 4],
       [5, 6, 7],
       [2, 3, 7]])

In [46]:
raja.transpose()

array([[2, 5, 2],
       [3, 6, 3],
       [4, 7, 7]])